"use client";
import { useEffect, useState } from "react";import { SettingsShell } from "../../../../components/settings/SettingsShell";import { Select as UiSelect } from "../../../../components/ui";import { api } from "../../../../lib/api";
type Pref={type:string;channel:string;enabled:string};const types=[['assigned','Task assignments'],['mention','Mentions'],['comment','Comments'],['watch','Task updates'],['project_status','Project status updates']];
type Delivery={digestFrequency:'off'|'daily'|'weekly';digestHour:number;quietFrom:number|null;quietTo:number|null};
export default function NotificationSettings(){const [rows,setRows]=useState<Pref[]>([]);const [d,setD]=useState<Delivery>({digestFrequency:'off',digestHour:9,quietFrom:null,quietTo:null});const [dSaved,setDSaved]=useState(false);
useEffect(()=>{api<Delivery>("/notifications/delivery-settings",{org:true}).then(x=>setD({digestFrequency:x.digestFrequency,digestHour:x.digestHour,quietFrom:x.quietFrom,quietTo:x.quietTo})).catch(()=>{})},[]);
async function saveDelivery(next:Delivery){setD(next);await api("/notifications/delivery-settings",{method:'PUT',org:true,body:JSON.stringify(next)});setDSaved(true);setTimeout(()=>setDSaved(false),1500)}
useEffect(()=>{api<Pref[]>("/me/notification-preferences",{org:true}).then(setRows).catch(()=>{})},[]);function enabled(type:string,channel:string){const r=rows.find(x=>x.type===type&&x.channel===channel);return r?r.enabled==='true':true}async function toggle(type:string,channel:string){const next=!enabled(type,channel);await api("/me/notification-preferences",{method:'PUT',org:true,body:JSON.stringify({type,channel,enabled:next})});setRows(r=>[...r.filter(x=>!(x.type===type&&x.channel===channel)),{type,channel,enabled:String(next)}])}return <SettingsShell><div className="settings-section"><h2>Notifications</h2><p>Choose what appears in Inbox and what is also delivered by email.</p><div className="pref-table"><div className="pref-head"><span>Activity</span><span>Inbox</span><span>Email</span></div>{types.map(([type,label])=><div className="pref-row" key={type}><span>{label}</span>{['inbox','email'].map(ch=><label className="switch" key={ch}><input type="checkbox" checked={enabled(type,ch)} onChange={()=>toggle(type,ch)}/><span/></label>)}</div>)}</div>
<h2 className="delivery-title">Email delivery</h2><p>Batch emails into a digest and pause them during quiet hours. Inbox and realtime updates are never delayed.</p>
<div className="delivery-grid">
  <label>Digest<UiSelect className="input" value={d.digestFrequency} onChange={e=>saveDelivery({...d,digestFrequency:e.target.value as Delivery['digestFrequency']})}><option value="off">Send each email immediately</option><option value="daily">Daily digest</option><option value="weekly">Weekly digest (Monday)</option></UiSelect></label>
  {d.digestFrequency!=='off'&&<label>Digest hour<UiSelect className="input" value={d.digestHour} onChange={e=>saveDelivery({...d,digestHour:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</UiSelect></label>}
  <label>Quiet hours<UiSelect className="input" value={d.quietFrom==null?'':String(d.quietFrom)} onChange={e=>{const v=e.target.value===''?null:Number(e.target.value);saveDelivery({...d,quietFrom:v,quietTo:v==null?null:(d.quietTo??7)})}}><option value="">Off</option>{Array.from({length:24},(_,h)=><option key={h} value={h}>from {String(h).padStart(2,'0')}:00</option>)}</UiSelect></label>
  {d.quietFrom!=null&&<label>until<UiSelect className="input" value={String(d.quietTo??7)} onChange={e=>saveDelivery({...d,quietTo:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</UiSelect></label>}
  {dSaved&&<span className="save-note">Saved</span>}
</div>
</div></SettingsShell>}
