"use client";

import { Button as UiButton } from "../../../../../components/ui";
import { Input as UiInput, Select as UiSelect } from "../../../../../components/ui";
import {useEffect,useMemo,useState,type ReactNode} from 'react';import {useParams} from 'next/navigation';import {api} from '../../../../../lib/api';import {ProjectChrome} from '../../../../../components/project/ProjectChrome';import {Icon} from '../../../../../components/ui/Icon';import {RuntimeStyle} from '../../../../../components/ui/RuntimeStyle';import {useModalDialog} from '../../../../../components/ui/useModalDialog';
type Project={id:string;name:string;keyPrefix:string;color?:string;health:string;status:string;privacy:string;version:number};type Item={id:string;statusCategory:string;priority:string;primaryOwnerUserId:string|null;sectionId:string|null;estimateMinutes:number|null;dueDate:string|null;createdAt:string;updatedAt:string};type Meta=Record<string,{actualMinutes?:number}>;type Member={userId:string;displayName:string};type Section={id:string;name:string};type Vel={sprints:{name:string;committed:number;completed:number}[];average:number};type CLT={avgCycleHours:number;avgLeadHours:number;items:any[]};
type ChartKind='bars'|'donut';type ChartSource='section'|'assignee'|'priority'|'status';type ChartFilter={status:'all'|'incomplete'|'done';due:'all'|'overdue'|'week'};
type Chart={id:string;title:string;kind:ChartKind;source:ChartSource;filter:ChartFilter};
type SavedView={id:string;name:string;viewType:string;filters?:Record<string,unknown>};
const DEFAULT_CHARTS:Chart[]=[{id:'c1',title:'Tasks by section',kind:'bars',source:'section',filter:{status:'all',due:'all'}},{id:'c2',title:'Tasks by assignee',kind:'donut',source:'assignee',filter:{status:'all',due:'all'}},{id:'c3',title:'Incomplete by priority',kind:'bars',source:'priority',filter:{status:'incomplete',due:'all'}}];
const SOURCE_LABEL:Record<ChartSource,string>={section:'Section',assignee:'Assignee',priority:'Priority',status:'Status'};
function filterCount(f:ChartFilter){return (f.status!=='all'?1:0)+(f.due!=='all'?1:0)}
function dayDiff(d:string|null){if(!d)return 999;const n=new Date();n.setHours(0,0,0,0);return Math.floor((new Date(d+'T00:00:00').getTime()-n.getTime())/86400000)}
export default function Dashboard(){const id=useParams().id as string;const [project,setProject]=useState<Project|null>(null);const[items,setItems]=useState<Item[]>([]);const[meta,setMeta]=useState<Meta>({});const[members,setMembers]=useState<Member[]>([]);const[sections,setSections]=useState<Section[]>([]);const[vel,setVel]=useState<Vel|null>(null);const[clt,setClt]=useState<CLT|null>(null);
const [charts,setCharts]=useState<Chart[]>(DEFAULT_CHARTS);const [savedId,setSavedId]=useState<string|null>(null);const [viewing,setViewing]=useState<Chart|null>(null);const [editing,setEditing]=useState<Chart|null>(null);const [isNew,setIsNew]=useState(false);
async function load(){const[p,i,md,m,s,v,c]=await Promise.all([api<Project>(`/projects/${id}`,{org:true}),api<Item[]>(`/projects/${id}/work-items?limit=500`,{org:true}).catch(()=>[]),api<Meta>(`/projects/${id}/list-metadata`,{org:true}).catch(()=>({})),api<Member[]>(`/projects/${id}/members`,{org:true}).catch(()=>[]),api<Section[]>(`/projects/${id}/sections`,{org:true}).catch(()=>[]),api<Vel>(`/projects/${id}/velocity`,{org:true}).catch(()=>null),api<CLT>(`/projects/${id}/cycle-lead-time`,{org:true}).catch(()=>null)]);setProject(p);setItems(i);setMeta(md);setMembers(m);setSections(s);setVel(v);setClt(c)}useEffect(()=>{load().catch(()=>{})},[id]);
useEffect(()=>{api<SavedView[]>(`/ui/saved-views?scopeType=project&scopeId=${id}`,{org:true}).then(views=>{const v=views.find(x=>x.viewType==='dashboard');if(!v)return;setSavedId(v.id);const saved=(v.filters as {charts?:Chart[]}|undefined)?.charts;if(Array.isArray(saved)&&saved.length)setCharts(saved.filter(c=>c&&c.id&&c.kind&&c.source))}).catch(()=>{})},[id]);
async function persist(next:Chart[]){setCharts(next);try{if(savedId)await api(`/ui/saved-views/${savedId}`,{method:'PATCH',org:true,body:JSON.stringify({filters:{charts:next}})});else{const created=await api<SavedView>('/ui/saved-views',{method:'POST',org:true,body:JSON.stringify({scopeType:'project',scopeId:id,name:'Dashboard charts',viewType:'dashboard',filters:{charts:next}})});setSavedId(created.id)}}catch{}}
const stats=useMemo(()=>{const done=items.filter(x=>x.statusCategory==='done').length,overdue=items.filter(x=>x.dueDate&&new Date(`${x.dueDate}T23:59:59`)<new Date()&&x.statusCategory!=='done').length;return{done,incomplete:items.length-done,overdue,total:items.length}},[items]);
const estimate=items.reduce((n,i)=>n+(i.estimateMinutes||0),0),actual=Object.values(meta).reduce((n,m)=>n+(m.actualMinutes||0),0);
function applyFilter(rows:Item[],f:ChartFilter){return rows.filter(x=>(f.status==='all'||(f.status==='done'?x.statusCategory==='done':x.statusCategory!=='done'))&&(f.due==='all'||(f.due==='overdue'?(x.dueDate&&dayDiff(x.dueDate)<0&&x.statusCategory!=='done'):(x.dueDate&&dayDiff(x.dueDate)>=0&&dayDiff(x.dueDate)<=7))))}
function seriesFor(c:Chart){const rows=applyFilter(items,c.filter);const key=(x:Item)=>c.source==='section'?(sections.find(s=>s.id===x.sectionId)?.name||'No section'):c.source==='assignee'?(members.find(m=>m.userId===x.primaryOwnerUserId)?.displayName||'Unassigned'):c.source==='priority'?x.priority:x.statusCategory.replace('_',' ');const m=new Map<string,number>();for(const x of rows)m.set(key(x),(m.get(key(x))||0)+1);return{data:[...m.entries()].map(([name,n])=>({name,n})).sort((a,b)=>b.n-a.n).slice(0,8),total:rows.length}}
function ChartBody({c,large}:{c:Chart;large?:boolean}){const {data,total}=seriesFor(c);if(!data.length)return <div className="widget-empty">No matching tasks.</div>;if(c.kind==='bars')return <div className={`bar-chart ${large?'bar-chart-large':''}`}>{data.map(x=><div key={x.name}><span>{x.name}</span><div><RuntimeStyle as="i" className="runtime-width" vars={{"--runtime-width":`${Math.max(5,(x.n/Math.max(1,total))*100)}%`}}/></div><strong>{x.n}</strong></div>)}</div>;const top=data[0];return <div className="donut-layout"><RuntimeStyle className="donut runtime-donut" vars={{"--runtime-progress":`${total?Math.round(((top?.n||0)/total)*100):0}%`}}><span>{total}</span></RuntimeStyle><div className="assignee-legend">{data.map(a=><div key={a.name}><span className="mini-avatar">{a.name[0]}</span><span>{a.name}</span><strong>{a.n}</strong></div>)}</div></div>}
function saveEditor(){if(!editing)return;const next=isNew?[...charts,editing]:charts.map(c=>c.id===editing.id?editing:c);persist(next);setEditing(null);setIsNew(false);setViewing(null)}
function removeChart(cid:string){persist(charts.filter(c=>c.id!==cid));setViewing(null);setEditing(null)}
function beginAdd(){setIsNew(true);setEditing({id:`c${Date.now()}`,title:'New chart',kind:'bars',source:'status',filter:{status:'all',due:'all'}})}
return <>{project&&<ProjectChrome project={project} view="dashboard" onProjectChange={load}/>}<div className="dashboard-toolbar"><div><h2>Dashboard</h2><p>Live project reporting with permission-safe work data.</p></div><UiButton variant="primary"  onClick={beginAdd}><Icon name="plus" size={16}/>Add chart</UiButton></div><div className="asana-dashboard-grid">
<section className="dashboard-widget span-2"><div className="widget-title"><strong>Project summary</strong></div><div className="dashboard-kpis"><div><strong>{stats.total}</strong><span>Total tasks</span></div><div><strong>{stats.incomplete}</strong><span>Incomplete</span></div><div><strong>{stats.done}</strong><span>Completed</span></div><div className={stats.overdue?'danger-kpi':''}><strong>{stats.overdue}</strong><span>Overdue</span></div></div></section>
{charts.map(c=><section className="dashboard-widget" key={c.id}><div className="widget-title chart-title-row"><button type="button" className="chart-open-btn" onClick={()=>setViewing(c)} aria-label={`View chart ${c.title}`}><strong>{c.title}</strong></button><span className="chart-title-actions"><span className="chart-filter-chip" data-on={filterCount(c.filter)>0}><Icon name="filter" size={12}/>{filterCount(c.filter)?`${filterCount(c.filter)} filter${filterCount(c.filter)>1?'s':''}`:'No filters'}</span><button className="icon-btn" aria-label={`Edit chart ${c.title}`} onClick={()=>{setIsNew(false);setEditing({...c})}}><Icon name="settings" size={14}/></button></span></div><ChartBody c={c}/></section>)}
<section className="dashboard-widget"><div className="widget-title"><strong>Completion & flow</strong></div><div className="completion-panel"><div className="progress-ring"><strong>{stats.total?Math.round(stats.done/stats.total*100):0}%</strong><span>complete</span></div><dl><div><dt>Average velocity</dt><dd>{vel?.average??0} pts</dd></div><div><dt>Avg cycle time</dt><dd>{clt?`${clt.avgCycleHours.toFixed(1)}h`:'—'}</dd></div><div><dt>Avg lead time</dt><dd>{clt?`${clt.avgLeadHours.toFixed(1)}h`:'—'}</dd></div></dl></div></section>
<section className="dashboard-widget"><div className="widget-title"><strong>Estimated vs actual time</strong></div><div className="time-bars"><div><span>Estimated</span><RuntimeStyle as="i" className="runtime-width" vars={{ "--runtime-width": `${Math.min(100,estimate/Math.max(1,estimate,actual)*100)}%` }} /><strong>{Math.round(estimate/60)}h</strong></div><div><span>Actual</span><RuntimeStyle as="i" className="actual runtime-width" vars={{ "--runtime-width": `${Math.min(100,actual/Math.max(1,estimate,actual)*100)}%` }} /><strong>{Math.round(actual/60)}h</strong></div></div></section>
</div>
{viewing&&!editing&&<ChartModal title="View chart" onClose={()=>setViewing(null)} actions={<button className="icon-btn" aria-label="Edit this chart" onClick={()=>{setIsNew(false);setEditing({...viewing})}}><Icon name="settings" size={16}/></button>}><div className="view-chart-body"><h3>{viewing.title}</h3><span className="chart-filter-chip" data-on={filterCount(viewing.filter)>0}><Icon name="filter" size={12}/>{filterCount(viewing.filter)?`${filterCount(viewing.filter)} filter${filterCount(viewing.filter)>1?'s':''}`:'No filters'}</span><ChartBody c={viewing} large/></div></ChartModal>}
{editing&&<ChartModal title={isNew?'Add chart':'Edit chart'} onClose={()=>{setEditing(null);setIsNew(false)}}><div className="chart-editor"><label className="field"><span>Title</span><UiInput className="input" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><div className="mini-form-grid"><label>Chart type<UiSelect className="input" value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as ChartKind})}><option value="bars">Bars</option><option value="donut">Donut</option></UiSelect></label><label>Group by<UiSelect className="input" value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value as ChartSource})}>{(Object.keys(SOURCE_LABEL) as ChartSource[]).map(s=><option key={s} value={s}>{SOURCE_LABEL[s]}</option>)}</UiSelect></label><label>Status filter<UiSelect className="input" value={editing.filter.status} onChange={e=>setEditing({...editing,filter:{...editing.filter,status:e.target.value as ChartFilter['status']}})}><option value="all">All tasks</option><option value="incomplete">Incomplete only</option><option value="done">Completed only</option></UiSelect></label><label>Due filter<UiSelect className="input" value={editing.filter.due} onChange={e=>setEditing({...editing,filter:{...editing.filter,due:e.target.value as ChartFilter['due']}})}><option value="all">Any due date</option><option value="overdue">Overdue</option><option value="week">Due this week</option></UiSelect></label></div><div className="chart-editor-preview"><span className="customize-label">Preview</span><ChartBody c={editing}/></div><div className="modal-foot">{!isNew&&<button className="text-button danger" onClick={()=>removeChart(editing.id)}>Remove chart</button>}<span className="spacer"/><UiButton variant="secondary" onClick={()=>{setEditing(null);setIsNew(false)}}>Cancel</UiButton><UiButton variant="primary" disabled={!editing.title.trim()} onClick={saveEditor}>{isNew?'Add chart':'Save chart'}</UiButton></div></div></ChartModal>}
</>}
function ChartModal({title,onClose,actions,children}:{title:string;onClose:()=>void;actions?:ReactNode;children:ReactNode}){const ref=useModalDialog<HTMLDivElement>(true,onClose);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div ref={ref} tabIndex={-1} className="chart-modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-title-row"><h2>{title}</h2><span className="chart-modal-actions">{actions}<button className="icon-btn" aria-label={`Close ${title.toLowerCase()}`} onClick={onClose}><Icon name="close"/></button></span></div>{children}</div></div>}
