"use client";

import { Button as UiButton, Input as UiInput, Select as UiSelect } from "../../../components/ui";
import { appPrompt } from "../../../components/ui/AppDialog";
import { useEffect, useState, useCallback } from "react";
import { api,ApiError } from "../../../lib/api";
import { useToast } from "../../../components/ui/Toast";
import { RuntimeStyle } from "../../../components/ui/RuntimeStyle";
import { Icon } from "../../../components/ui/Icon";

type Portfolio = { id: string; name: string };
type Column={id:string;key:string;name:string;type:string;rank:number};
type ProjRow = { projectId: string | null; name: string; redacted: boolean; progress: number | null; done: number | null; total: number | null; start: string | null; end: string | null; ownerUserId?:string|null;status?:string;health?:string;updatedAt?:string|null;budgetCents?:number|null;serviceLine?:string|null;customFields?:Record<string,unknown> };
type Rollup = { portfolio: { id:string;name: string }; columns:Column[];projects: ProjRow[]; aggregateProgress: number; aggregateDone: number; aggregateTotal: number; milestones: { total: number; hit: number; missed: number; overdue: number } };
type Milestone = { id: string; name: string; dueDate: string | null; status: string };
type Project = { id: string; name: string };type Initiative = { id: string; name: string; status: string };type Person={id:string;displayName:string};

export default function PortfoliosPage() {
  const toast = useToast(); const [portfolios, setPortfolios] = useState<Portfolio[]>([]);const [sel, setSel] = useState<string | null>(null);const [roll, setRoll] = useState<Rollup | null>(null);const [ms, setMs] = useState<Milestone[]>([]);const [inits, setInits] = useState<Initiative[]>([]);const [projects, setProjects] = useState<Project[]>([]);const [people,setPeople]=useState<Person[]>([]);const [pick, setPick] = useState("");
  const loadList = useCallback(async () => setPortfolios(await api<Portfolio[]>("/portfolios", { org: true }).catch(() => [])), []);
  useEffect(() => { loadList(); api<Project[]>("/projects", { org: true }).then(setProjects).catch(() => {});api<Person[]>('/directory/members',{org:true}).then(setPeople).catch(()=>{}) }, [loadList]);
  const open = useCallback(async (id: string) => {setSel(id);setRoll(await api<Rollup>(`/portfolios/${id}/rollup`, { org: true }).catch(() => null));setMs(await api<Milestone[]>(`/portfolios/${id}/milestones`, { org: true }).catch(() => []));setInits(await api<Initiative[]>(`/portfolios/${id}/initiatives`, { org: true }).catch(() => []));}, []);
  async function create() { const name = await appPrompt("Portfolio name"); if (!name) return; const row=await api<Portfolio>("/portfolios", { method: "POST", org: true, body: JSON.stringify({ name }) }); await loadList(); await open(row.id); }
  async function addProject() { if (!sel || !pick) return; try{await api(`/portfolios/${sel}/projects`, { method: "POST", org: true, body: JSON.stringify({ projectId: pick }) }); setPick(""); open(sel);}catch(e){toast({message:e instanceof ApiError?e.message:'Could not add project',tone:'error'})} }
  async function updateProject(row:ProjRow,patch:{budgetCents?:number|null;serviceLine?:string|null;customFields?:Record<string,unknown>}){if(!sel||!row.projectId)return;await api(`/portfolios/${sel}/projects/${row.projectId}`,{method:'PATCH',org:true,body:JSON.stringify(patch)});await open(sel)}
  async function addColumn(){if(!sel)return;const name=await appPrompt('Column name');if(!name?.trim())return;const type=await appPrompt('Column type: text, number, currency, date, or select','text');if(!type)return;try{await api(`/portfolios/${sel}/columns`,{method:'POST',org:true,body:JSON.stringify({name:name.trim(),type})});open(sel)}catch(e){toast({message:e instanceof ApiError?e.message:'Could not create column',tone:'error'})}}
  async function removeColumn(col:Column){if(!sel)return;try{await api(`/portfolios/${sel}/columns/${col.id}`,{method:'DELETE',org:true});open(sel)}catch(e){toast({message:e instanceof ApiError?e.message:'Could not remove the column'})}}
  async function addMilestone() { if (!sel) return; const name = await appPrompt("Milestone name"); if (!name) return; const dueDate = await appPrompt("Due date (YYYY-MM-DD)") || undefined; try { await api(`/portfolios/${sel}/milestones`, { method: "POST", org: true, body: JSON.stringify({ name, dueDate }) }); open(sel); } catch (e) { toast({ message: e instanceof ApiError ? e.message : "Could not add the milestone" }); } }
  async function markMs(id: string, status: string) { try { await api(`/milestones/${id}/status`, { method: "POST", org: true, body: JSON.stringify({ status }) }); if (sel) open(sel); } catch (e) { toast({ message: e instanceof ApiError ? e.message : "Could not update the milestone" }); } }
  async function addInitiative() { if (!sel) return; const name = await appPrompt("Initiative name"); if (!name) return; try { await api(`/portfolios/${sel}/initiatives`, { method: "POST", org: true, body: JSON.stringify({ name }) }); open(sel); } catch (e) { toast({ message: e instanceof ApiError ? e.message : "Could not add the initiative" }); } }
  const ownerName=(id?:string|null)=>people.find(p=>p.id===id)?.displayName||'—';
  return <><div className="portfolio-page-head"><h1 className="page-title">Portfolios</h1><UiButton variant="primary" onClick={create}><Icon name="plus" size={15}/>New portfolio</UiButton></div><div className="builder-grid"><div>{!roll&&<p className="muted">Select a portfolio for the executive rollup.</p>}{roll&&<><div className="metric-card"><div className="kpi"><div><span className="n">{roll.aggregateProgress}%</span><span className="l">Overall progress</span></div><div><span className="n">{roll.aggregateDone}/{roll.aggregateTotal}</span><span className="l">Items done</span></div><div><span className="n">{roll.milestones.hit}/{roll.milestones.total}</span><span className="l">Milestones hit</span></div><div><span className="n" data-tone={roll.milestones.overdue?"error":undefined}>{roll.milestones.overdue}</span><span className="l">Overdue</span></div></div></div>
    <div className="portfolio-toolbar"><UiSelect className="input" value={pick} onChange={e=>setPick(e.target.value)}><option value="">Add project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</UiSelect><UiButton variant="secondary" onClick={addProject} disabled={!pick}>Add</UiButton><span className="spacer"/><UiButton variant="secondary" onClick={addColumn}><Icon name="plus" size={14}/>Customize columns</UiButton></div>
    <div className="portfolio-table-scroll"><table className="exec-table portfolio-rich-table"><thead><tr><th>Project</th><th>Owner</th><th>Status</th><th>Progress</th><th>Budget</th><th>Service line</th>{roll.columns.map(c=><th key={c.id}><span>{c.name}</span><button aria-label={`Remove ${c.name} column`} onClick={()=>removeColumn(c)}><Icon name="close" size={12}/></button></th>)}<th>Dates</th></tr></thead><tbody>{roll.projects.map((p,i)=><tr key={p.projectId||i}><td data-redacted={p.redacted||undefined}>{p.name}</td><td>{p.redacted?'—':ownerName(p.ownerUserId)}</td><td>{p.redacted?'—':<span className={`health-chip health-${p.health}`}><i/>{(p.status||'active').replaceAll('_',' ')}</span>}</td><td>{p.redacted?'—':<div className="prog-bar"><RuntimeStyle className="prog-fill runtime-width" vars={{"--runtime-width":`${p.progress}%`}}/></div>}</td><td>{p.redacted||!p.projectId?'—':<UiInput className="portfolio-cell-input" inputMode="decimal" defaultValue={p.budgetCents==null?'':String(p.budgetCents/100)} placeholder="0" onBlur={e=>{const v=e.target.value.trim();updateProject(p,{budgetCents:v===''?null:Math.max(0,Math.round(Number(v)*100))})}} aria-label={`Budget for ${p.name}`}/>}</td><td>{p.redacted||!p.projectId?'—':<UiInput className="portfolio-cell-input" defaultValue={p.serviceLine||''} placeholder="Service line" onBlur={e=>updateProject(p,{serviceLine:e.target.value.trim()||null})} aria-label={`Service line for ${p.name}`}/>}</td>{roll.columns.map(c=><td key={c.id}>{p.redacted||!p.projectId?'—':<CustomCell row={p} column={c} onSave={(value)=>updateProject(p,{customFields:{...(p.customFields||{}),[c.key]:value}})}/>}</td>)}<td className="muted">{p.redacted?'—':`${p.start??'?'} → ${p.end??'?'}`}</td></tr>)}</tbody></table></div>
    <div className="portfolio-secondary-grid"><div><div className="section-title-row"><h3>Milestones</h3><UiButton variant="tertiary" onClick={addMilestone}>+ Add</UiButton></div>{ms.map(m=><div key={m.id} className="portfolio-small-row"><span>{m.name} <span className="muted">{m.dueDate}</span></span><span><span className={`pill ${m.status==='hit'?'approved':m.status==='missed'?'rejected':'open'}`}>{m.status}</span>{m.status==='planned'&&<UiButton variant="tertiary" size="compact" onClick={()=>markMs(m.id,'hit')}>✓</UiButton>}</span></div>)}</div><div><div className="section-title-row"><h3>Initiatives</h3><UiButton variant="tertiary" onClick={addInitiative}>+ Add</UiButton></div>{inits.map(it=><div key={it.id} className="portfolio-small-row"><span>{it.name}</span><span className="pill open">{it.status}</span></div>)}</div></div></>}</div>
    <div className="gpanel"><h3>Portfolios</h3>{portfolios.map(p=><UiButton variant="tertiary" key={p.id} className="ui-selection-row" data-selected={sel===p.id||undefined} onClick={()=>open(p.id)}>{p.name}</UiButton>)}</div></div></>;
}
function CustomCell({row,column,onSave}:{row:ProjRow;column:Column;onSave:(value:unknown)=>void}){const value=row.customFields?.[column.key];if(column.type==='select')return <UiInput className="portfolio-cell-input" defaultValue={String(value??'')} onBlur={e=>onSave(e.target.value)} placeholder="Value"/>;if(column.type==='number'||column.type==='currency')return <UiInput className="portfolio-cell-input" inputMode="decimal" defaultValue={String(value??'')} onBlur={e=>onSave(e.target.value===''?null:Number(e.target.value))} placeholder="0"/>;if(column.type==='date')return <UiInput className="portfolio-cell-input" type="date" defaultValue={String(value??'')} onBlur={e=>onSave(e.target.value||null)}/>;return <UiInput className="portfolio-cell-input" defaultValue={String(value??'')} onBlur={e=>onSave(e.target.value)} placeholder={column.name}/>}
