"use client";

import { Button as UiButton, Input as UiInput, Select as UiSelect } from "../../../components/ui";
import { appPrompt } from "../../../components/ui/AppDialog";
import {useEffect,useMemo,useState} from 'react';
import {api,ApiError} from '../../../lib/api';
import {Icon,type IconName} from '../../../components/ui/Icon';
import {useToast} from '../../../components/ui/Toast';
import {useModalDialog} from '../../../components/ui/useModalDialog';
import {RuntimeStyle} from '../../../components/ui/RuntimeStyle';
import {useTheme} from '../../../components/theme/ThemeProvider';

type Project={id:string;name:string;keyPrefix:string;status:string;health:string;privacy:string;workspaceId:string;ownerUserId:string|null;teamId:string|null;updatedAt:string;color?:string;icon?:string|null};
type Profile={id:string;displayName:string;email:string};type Workspace={id:string;name:string};type Person={id:string;displayName:string;email:string};type Team={id:string;name:string;memberCount:number};type Member={id:string;userId:string;displayName:string};
type PortfolioLink={portfolioId:string;portfolioName:string;projectId:string};type Favorite={projectId:string};type Template={id:string;name:string;kind:string};

export default function Projects(){
  const theme=useTheme(); const toast=useToast();
  const [projects,setProjects]=useState<Project[]>([]);const [workspaces,setWs]=useState<Workspace[]>([]);const [people,setPeople]=useState<Person[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [members,setMembers]=useState<Record<string,Member[]>>({});const [me,setMe]=useState<Profile|null>(null);
  const [portfolioLinks,setPortfolioLinks]=useState<PortfolioLink[]>([]);const [favorites,setFavorites]=useState<Set<string>>(new Set());const [templates,setTemplates]=useState<Template[]>([]);const [templateWorkspace,setTemplateWorkspace]=useState('');
  const [q,setQ]=useState('');const [owner,setOwner]=useState('');const [member,setMember]=useState('');const [team,setTeam]=useState('');const [status,setStatus]=useState('');const [portfolio,setPortfolio]=useState('');const [sort,setSort]=useState<'modified_desc'|'modified_asc'|'name'>('modified_desc');const [create,setCreate]=useState(false);
  const navPrefs=(theme.preferences.navigationPreferences||{}) as Record<string,unknown>;const templatesDismissed=navPrefs.templateSuggestionsDismissed===true;const showRowNumbers=theme.preferences.showRowNumbers;
  async function createWorkspace(){const name=await appPrompt('New workspace name');if(!name)return;try{await api('/workspaces',{method:'POST',org:true,body:JSON.stringify({name})});toast({message:'Workspace created'});await load();}catch(e){toast({message:e instanceof ApiError?e.message:'Could not create workspace'});}}
  async function load(){const [p,w,u,t,profile,pl,fav,tpl]=await Promise.all([api<Project[]>('/projects',{org:true}),api<Workspace[]>('/workspaces',{org:true}),api<Person[]>('/directory/members',{org:true}),api<Team[]>('/directory/teams',{org:true}),api<Profile>('/me/profile',{org:true}),api<PortfolioLink[]>('/portfolio-projects',{org:true}).catch(()=>[]),api<Favorite[]>('/projects/favorites',{org:true}).catch(()=>[]),api<Template[]>('/templates/suggestions',{org:true}).catch(()=>[])]);setProjects(p);setWs(w);setPeople(u);setTeams(t);setMe(profile);setPortfolioLinks(pl);setFavorites(new Set(fav.map(x=>x.projectId)));setTemplates(tpl);if(!templateWorkspace&&w[0])setTemplateWorkspace(w[0].id);const pairs=await Promise.all(p.map(async x=>[x.id,await api<Member[]>(`/projects/${x.id}/members`,{org:true}).catch(()=>[])] as const));setMembers(Object.fromEntries(pairs))}
  useEffect(()=>{load().catch(()=>{})},[]);
  const portfolioNames=useMemo(()=>{const map=new Map<string,string[]>();for(const l of portfolioLinks)map.set(l.projectId,[...(map.get(l.projectId)||[]),l.portfolioName]);return map},[portfolioLinks]);
  const portfolioOptions=useMemo(()=>Array.from(new Map(portfolioLinks.map(x=>[x.portfolioId,x.portfolioName])).entries()),[portfolioLinks]);
  const visible=useMemo(()=>projects.filter(p=>`${p.name} ${p.keyPrefix}`.toLowerCase().includes(q.toLowerCase())&&(!owner||p.ownerUserId===owner)&&(!member||(members[p.id]||[]).some(m=>m.userId===member))&&(!team||p.teamId===team)&&(!status||p.status===status)&&(!portfolio||portfolioLinks.some(x=>x.projectId===p.id&&x.portfolioId===portfolio))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='modified_asc'?+new Date(a.updatedAt)-+new Date(b.updatedAt):+new Date(b.updatedAt)-+new Date(a.updatedAt)),[projects,q,owner,member,team,status,portfolio,sort,members,portfolioLinks]);
  async function toggleFavorite(projectId:string){const next=!favorites.has(projectId);setFavorites(prev=>{const n=new Set(prev);next?n.add(projectId):n.delete(projectId);return n});try{await api(`/projects/${projectId}/favorite`,{method:'PUT',org:true,body:JSON.stringify({favorite:next})})}catch{setFavorites(prev=>{const n=new Set(prev);next?n.delete(projectId):n.add(projectId);return n})}}
  async function useTemplate(tpl:Template){if(!templateWorkspace){toast({message:'Choose a target workspace first',tone:'warning'});return;}const name=await appPrompt('Project name',tpl.name);if(!name?.trim())return;try{const result=await api<{projectId:string}>(`/templates/${tpl.id}/use-project`,{method:'POST',org:true,body:JSON.stringify({workspaceId:templateWorkspace,name:name.trim()})});location.assign(`/projects/${result.projectId}`)}catch(e){toast({message:e instanceof ApiError?e.message:'Could not use template',tone:'error'})}}
  function dismissTemplates(){theme.setPreferences({navigationPreferences:{...navPrefs,templateSuggestionsDismissed:true}})}
  return <div className="browse-projects"><header className="asana-page-title"><h1>Browse projects</h1><div className="ui-static-a76d597a"><UiButton variant="secondary" onClick={createWorkspace}><Icon name="plus" size={16}/>New workspace</UiButton><UiButton variant="primary" disabled={!workspaces.length} title={workspaces.length?'':'Create a workspace first'} onClick={()=>setCreate(true)}><Icon name="plus" size={16}/>Create project</UiButton></div></header>
    {!templatesDismissed&&templates.length>0&&<section className="project-template-strip"><div className="project-template-strip-head"><div><strong>Start faster with a template</strong><span>Published workspace templates create a real project with the configured sections and tasks.</span></div><div><UiSelect aria-label="Template target workspace" value={templateWorkspace} onChange={e=>setTemplateWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</UiSelect><a className="btn btn-secondary" href="/templates">Template gallery</a><button className="icon-btn" aria-label="Dismiss template suggestions" onClick={dismissTemplates}><Icon name="close" size={16}/></button></div></div><div className="project-template-cards">{templates.slice(0,4).map(t=><button key={t.id} onClick={()=>useTemplate(t)}><span className="template-project-icon"><Icon name="projects" size={18}/></span><span><b>{t.name}</b><small>{t.kind} template</small></span><Icon name="chevronRight" size={15}/></button>)}</div></section>}
    <div className="browse-controls"><label className="browse-search"><Icon name="search" size={16}/><UiInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a project"/></label><div className="browse-filters"><label>Owner<UiSelect value={owner} onChange={e=>setOwner(e.target.value)}><option value="">All</option>{people.map(x=><option value={x.id} key={x.id}>{x.displayName}</option>)}</UiSelect></label><label>Members<UiSelect value={member} onChange={e=>setMember(e.target.value)}><option value="">All</option>{people.map(x=><option value={x.id} key={x.id}>{x.displayName}</option>)}</UiSelect></label><label>Teams<UiSelect value={team} onChange={e=>setTeam(e.target.value)}><option value="">All</option>{teams.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</UiSelect></label><label>Portfolios<UiSelect value={portfolio} onChange={e=>setPortfolio(e.target.value)}><option value="">All</option>{portfolioOptions.map(([id,name])=><option value={id} key={id}>{name}</option>)}</UiSelect></label><label>Status<UiSelect value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="archived">Archived</option></UiSelect></label><label>Sort<UiSelect value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="modified_desc">Last modified · newest</option><option value="modified_asc">Last modified · oldest</option><option value="name">Name</option></UiSelect></label></div></div>
    <div className="browse-table"><div className="browse-table-head"><span>Name</span><span>Members</span><span>Team</span><span>Portfolios</span><span>Status</span><button className="table-sort-head" onClick={()=>setSort(sort==='modified_desc'?'modified_asc':'modified_desc')} aria-label="Sort by last modified">Last modified <Icon name="sort" size={13}/></button><span/></div>{visible.map(p=><div className="browse-project-row" key={p.id}><a href={`/projects/${p.id}`} className="browse-name">{showRowNumbers?<span className="row-number" aria-hidden="true">{visible.indexOf(p)+1}</span>:null}<RuntimeStyle as="span" className="project-glyph big runtime-bg" vars={{ "--runtime-bg": p.color }}>{p.icon&&p.icon!=='project'?<Icon name={p.icon as IconName} size={17}/>:p.name.slice(0,1)}</RuntimeStyle><span><strong>{p.name}</strong><small>{p.keyPrefix} · {p.privacy}</small></span></a><div className="browse-member-faces">{(members[p.id]||[]).slice(0,4).map(m=><span title={m.displayName} key={m.id}>{m.displayName.slice(0,1)}</span>)}{(members[p.id]||[]).length>4&&<em>+{members[p.id].length-4}</em>}</div><span>{teams.find(t=>t.id===p.teamId)?.name||'—'}</span><span className="browse-portfolio-names">{(portfolioNames.get(p.id)||[]).length?(portfolioNames.get(p.id)||[]).join(', '):'—'}</span><span className={`health-chip health-${p.health}`}><i/>{p.status.replaceAll('_',' ')}</span><span>{new Date(p.updatedAt).toLocaleDateString()}</span><div className="browse-row-actions"><button className="icon-btn" data-on={favorites.has(p.id)} onClick={()=>toggleFavorite(p.id)} aria-label={favorites.has(p.id)?`Unfavorite ${p.name}`:`Favorite ${p.name}`}><Icon name="star" size={16}/></button><UiButton variant="secondary" size="compact" data-joined={Boolean(me&&(members[p.id]||[]).some(m=>m.userId===me.id))} onClick={async()=>{const joined=Boolean(me&&(members[p.id]||[]).some(m=>m.userId===me.id));await api(`/projects/${p.id}/join`,{method:joined?'DELETE':'POST',org:true});load()}}>{me&&(members[p.id]||[]).some(m=>m.userId===me.id)?'Joined':'Join'}</UiButton></div></div>)}{!visible.length&&<div className="table-empty">No projects match these filters.</div>}</div>{create&&<CreateProjectModal workspaces={workspaces} onClose={()=>setCreate(false)} onCreated={()=>{setCreate(false);load()}}/>}
  </div>;
}

function CreateProjectModal({workspaces,onClose,onCreated}:{workspaces:Workspace[];onClose:()=>void;onCreated:()=>void}){const toast=useToast();const [name,setName]=useState('');const [key,setKey]=useState('');const [ws,setWs]=useState(workspaces[0]?.id||'');const [privacy,setPrivacy]=useState('workspace');const dialogRef=useModalDialog<HTMLDivElement>(true,onClose,'input');async function submit(){try{await api('/projects',{method:'POST',org:true,body:JSON.stringify({name,keyPrefix:key,workspaceId:ws,privacy})});toast({message:'Project created'});onCreated();}catch(e){toast({message:e instanceof ApiError?e.message:'Could not create project'});}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={dialogRef} tabIndex={-1} className="modal-card project-create-modal" role="dialog" aria-modal="true" aria-labelledby="create-project-title"><div className="modal-title-row"><h2 id="create-project-title">Create project</h2><button className="icon-btn" aria-label="Close create project dialog" onClick={onClose}><Icon name="close"/></button></div><label>Project name<UiInput className="input" value={name} onChange={e=>{setName(e.target.value);if(!key)setKey(e.target.value.replace(/[^a-zA-Z0-9]/g,'').slice(0,5).toUpperCase())}}/></label><label>Key<UiInput className="input" value={key} onChange={e=>setKey(e.target.value.toUpperCase())}/></label><label>Workspace<UiSelect className="input" value={ws} onChange={e=>setWs(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</UiSelect></label><label>Privacy<UiSelect className="input" value={privacy} onChange={e=>setPrivacy(e.target.value)}><option value="workspace">Workspace</option><option value="private">Private</option></UiSelect></label><div className="modal-actions"><UiButton variant="secondary" onClick={onClose}>Cancel</UiButton><UiButton variant="primary" disabled={!name||!key||!ws} onClick={submit}>Create project</UiButton></div></div></div>}
