"use client";

import { Input as UiInput, Select as UiSelect } from "../../../../../components/ui";
import { appPrompt } from "../../../../../components/ui/AppDialog";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "../../../../../lib/api";
import { ProjectChrome } from "../../../../../components/project/ProjectChrome";
import { TaskDrawer } from "../../../../../components/work/TaskDrawer";
import { Icon } from "../../../../../components/ui/Icon";

type Item = { id:string; key:string; title:string; startDate:string|null; dueDate:string|null; statusCategory:string };
type Edge = { id:string; from:string; to:string };
type Project = { id:string; name:string; keyPrefix:string; color?:string; health:string; status:string; privacy:string; version:number; description?:string|null; startDate?:string|null; dueDate?:string|null };
const day=86400000; const parse=(s:string)=>new Date(`${s}T00:00:00Z`).getTime();
export default function TimelinePage(){
 const id=useParams().id as string; const [project,setProject]=useState<Project|null>(null); const [items,setItems]=useState<Item[]>([]); const [edges,setEdges]=useState<Edge[]>([]); const [pxPerDay,setPxPerDay]=useState(16); const [openId,setOpenId]=useState<string|null>(null); const [search,setSearch]=useState(""); const [hideDone,setHideDone]=useState(false); const [sortBy,setSortBy]=useState<"date"|"name">("date");
 const [loadError,setLoadError]=useState('');
 async function load(){const from=new Date(Date.now()-200*day).toISOString().slice(0,10),to=new Date(Date.now()+400*day).toISOString().slice(0,10);try{const [p,i,e]=await Promise.all([api<Project>(`/projects/${id}`,{org:true}),api<Item[]>(`/calendar/range?from=${from}&to=${to}&projectId=${id}`,{org:true}).catch(()=>[]),api<{edges:Edge[]}>(`/projects/${id}/dependency-graph`,{org:true}).catch(()=>({edges:[]}))]);setProject(p);setItems(i);setEdges(e.edges);setLoadError('')}catch(err){setLoadError(err instanceof Error?err.message:"Could not load this project's timeline.")}}
 useEffect(()=>{load()},[id]);
 const model=useMemo(()=>{const dated=items.filter(i=>i.dueDate&&`${i.key} ${i.title}`.toLowerCase().includes(search.toLowerCase())&&(!hideDone||i.statusCategory!=="done")).sort((a,b)=>sortBy==="name"?a.title.localeCompare(b.title):parse(a.startDate??a.dueDate!)-parse(b.startDate??b.dueDate!));if(!dated.length)return null;const starts=dated.map(i=>parse(i.startDate??i.dueDate!)),ends=dated.map(i=>parse(i.dueDate!));const min=Math.min(...starts),max=Math.max(...ends),leftPad=230,rowH=36,top=48;const xOf=(t:number)=>leftPad+((t-min)/day)*pxPerDay;const rowOf=new Map(dated.map((i,n)=>[i.id,n]));const width=Math.max(900,xOf(max)+80),height=top+dated.length*rowH+30;const months:{x:number;label:string}[]=[];const d=new Date(min);d.setUTCDate(1);while(d.getTime()<=max+31*day){months.push({x:xOf(d.getTime()),label:d.toLocaleString("en",{month:"short",year:"2-digit",timeZone:"UTC"})});d.setUTCMonth(d.getUTCMonth()+1)}return{dated,min,max,leftPad,rowH,top,xOf,rowOf,width,height,months}},[items,edges,pxPerDay,search,hideDone,sortBy]);
 async function saveView(){const name=await appPrompt("View name","Timeline view");if(!name)return;const share=await appPrompt('Share with the whole organization? Type "org" to share, or leave blank to keep it just for you.','');const ownershipTier=(share||'').trim().toLowerCase()==='org'?'org':'personal';await api("/ui/saved-views",{method:"POST",org:true,body:JSON.stringify({scopeType:"project",scopeId:id,name,viewType:"timeline",filters:{search,hideDone},sortSpec:{sortBy},options:{pxPerDay},ownershipTier})})}
 function goToday(){if(!model)return;const node=document.querySelector<HTMLElement>(".tl-wrap");if(node)node.scrollLeft=Math.max(0,model.xOf(Date.now())-node.clientWidth/2)}
 if(!project) return <div className="project-loading">{loadError||"Loading timeline…"}{loadError&&<button className="text-button" onClick={load}>Retry</button>}</div>;
 return <><ProjectChrome project={project} view="timeline" onProjectChange={load}/><div className="view-toolbar project-toolbar"><button className="toolbar-button" onClick={goToday}>Today</button><label className="toolbar-button"><Icon name="calendar" size={15}/><UiSelect aria-label="Timeline zoom preset" value={pxPerDay>=24?'weeks':pxPerDay>=12?'months':'quarters'} onChange={e=>setPxPerDay(e.target.value==='weeks'?28:e.target.value==='months'?16:7)}><option value="weeks">Weeks</option><option value="months">Months</option><option value="quarters">Quarters</option></UiSelect></label><button className="toolbar-button" aria-label="Zoom out" title="Zoom out" onClick={()=>setPxPerDay(p=>Math.max(6,p-4))}>−</button><button className="toolbar-button" aria-label="Zoom in" title="Zoom in" onClick={()=>setPxPerDay(p=>Math.min(48,p+4))}>+</button><button className="toolbar-button" data-on={hideDone} onClick={()=>setHideDone(!hideDone)}><Icon name="filter" size={15}/>{hideDone?"Incomplete only":"Filter"}</button><label className="toolbar-button"><Icon name="sort" size={15}/>Sort<UiSelect value={sortBy} onChange={e=>setSortBy(e.target.value as any)}><option value="date">Start date</option><option value="name">Name</option></UiSelect></label><span className="toolbar-button static-control"><Icon name="sliders" size={15}/>Options: {pxPerDay}px/day</span><label className="toolbar-search"><Icon name="search" size={15}/><UiInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks"/></label><button className="toolbar-button primary-link" onClick={saveView}>Save view</button></div>
 {!model?<div className="empty asana-empty">No tasks with dates yet. Add start and due dates to plan the timeline.</div>:<div className="asana-timeline-shell"><div className="tl-wrap"><svg width={model.width} height={model.height} className="ui-static-2a1b75c9"><defs><marker id="tlarrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="var(--ink-3)"/></marker></defs>{model.months.map((m,i)=><g key={i}><line className="tl-grid" x1={m.x} y1={model.top-12} x2={m.x} y2={model.height-10}/><text className="tl-month" x={m.x+3} y={model.top-16}>{m.label}</text></g>)}{model.dated.map((it,idx)=>{const y=model.top+idx*model.rowH,s=parse(it.startDate??it.dueDate!),e=parse(it.dueDate!),milestone=!it.startDate||s===e,x1=model.xOf(s),x2=model.xOf(e);return <g key={it.id} className="timeline-click-row" onClick={()=>setOpenId(it.id)}><text className="tl-label" x={10} y={y+17}>{it.key}  {it.title.slice(0,24)}</text>{milestone?<rect className="tl-milestone" x={x2-6} y={y+5} width={12} height={12} transform={`rotate(45 ${x2} ${y+11})`}/>:<rect className={`tl-bar ${it.statusCategory==="done"?"done":""}`} x={x1} y={y+4} width={Math.max(8,x2-x1)} height={18} rx={5}/>}</g>})}{edges.map(edge=>{const a=model.rowOf.get(edge.from),b=model.rowOf.get(edge.to);if(a==null||b==null)return null;const pa=model.dated[a],pb=model.dated[b],ax=model.xOf(parse(pa.dueDate!)),ay=model.top+a*model.rowH+12,bx=model.xOf(parse(pb.startDate??pb.dueDate!)),by=model.top+b*model.rowH+12;return <path key={edge.id} className="tl-dep" d={`M${ax},${ay} C${ax+20},${ay} ${bx-20},${by} ${bx},${by}`}/>})}</svg></div></div>}
 {openId&&<TaskDrawer id={openId} onClose={()=>setOpenId(null)} onSaved={load}/>}</>;
}
