"use client";
import { useEffect, useMemo, useState } from "react";
import { api } from "../../../lib/api";
import { Icon } from "../../../components/ui/Icon";
import { TaskDrawer } from "../../../components/work/TaskDrawer";
import { useTheme } from "../../../components/theme/ThemeProvider";
import { RuntimeStyle } from "../../../components/ui/RuntimeStyle";
import { OnboardingChecklist } from "../../../components/onboarding/OnboardingChecklist";

type Profile={id:string;displayName:string;email:string};type Item={id:string;key:string;title:string;statusCategory:string;status:string;dueDate:string|null;owningProjectId:string;updatedAt:string};type Delegated=Item&{ownerDisplayName:string|null};type Project={id:string;name:string;color?:string;health:string;keyPrefix:string};type Person={id:string;displayName:string;email:string};type Widget={widgetKey:string;enabled:boolean;sortOrder:number;size:string};
function dateKey(d:string|null){if(!d)return 99;const x=new Date(d+'T00:00:00').getTime();const now=new Date();now.setHours(0,0,0,0);return Math.round((x-now.getTime())/86400000)}
export default function HomePage(){const t=useTheme();const [profile,setProfile]=useState<Profile|null>(null);const [items,setItems]=useState<Item[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [people,setPeople]=useState<Person[]>([]);const [widgets,setWidgets]=useState<Widget[]>([]);const [tab,setTab]=useState<'upcoming'|'overdue'|'completed'>('upcoming');const [openId,setOpenId]=useState<string|null>(null);const [customize,setCustomize]=useState(false);const [delegated,setDelegated]=useState<Delegated[]>([]);const [peopleStats,setPeopleStats]=useState<Record<string,{overdue:number;completed:number;upcoming:number}>>({});const [weekMenu,setWeekMenu]=useState(false);
const nav=(t.preferences.navigationPreferences||{}) as {homeStatsWindow?:'week'|'month'};const statsWindow=nav.homeStatsWindow==='month'?'month':'week';
function setStatsWindow(w:'week'|'month'){t.setPreferences({navigationPreferences:{...(t.preferences.navigationPreferences||{}),homeStatsWindow:w}});setWeekMenu(false)}
async function load(){const [a,b,c,d,p,g,ps]=await Promise.all([api<Item[]>('/my-work',{org:true}),api<Project[]>('/projects',{org:true}),api<Person[]>('/directory/members',{org:true}),api<Widget[]>('/ui/home-widgets',{org:true}),api<Profile>('/me/profile',{org:true}).catch(()=>null),api<Delegated[]>('/my-work/delegated',{org:true}).catch(()=>[]),api<{userId:string;overdue:number;completed:number;upcoming:number}[]>('/directory/overview',{org:true}).catch(()=>[])]);setItems(a);setProjects(b);setPeople(c);setWidgets(d);setProfile(p);setDelegated(g);setPeopleStats(Object.fromEntries(ps.map(x=>[x.userId,x])))}useEffect(()=>{load().catch(()=>{})},[]);
const visible=useMemo(()=>items.filter(x=>tab==='completed'?x.statusCategory==='done':tab==='overdue'?x.statusCategory!=='done'&&dateKey(x.dueDate)<0:x.statusCategory!=='done'&&dateKey(x.dueDate)>=0).slice(0,12),[items,tab]);const enabled=(k:string)=>widgets.find(w=>w.widgetKey===k)?.enabled!==false;
async function toggleWidget(k:string){const current=widgets.length?widgets:[{widgetKey:'my_tasks',enabled:true,sortOrder:0,size:'large'},{widgetKey:'assigned',enabled:true,sortOrder:1,size:'large'},{widgetKey:'projects',enabled:true,sortOrder:2,size:'large'},{widgetKey:'people',enabled:true,sortOrder:3,size:'medium'}];const next=current.map(w=>w.widgetKey===k?{...w,enabled:!w.enabled}:w);setWidgets(next);await api('/ui/home-widgets',{method:'PUT',org:true,body:JSON.stringify({widgets:next})}).catch(()=>{})}
const now=new Date();const greeting=now.getHours()<12?'Good morning':now.getHours()<17?'Good afternoon':'Good evening';const windowDays=statsWindow==='month'?30:7;const windowStart=Date.now()-windowDays*86400000;const completedInWindow=items.filter(x=>x.statusCategory==='done'&&new Date(x.updatedAt).getTime()>=windowStart).length;return <div className={`asana-home bg-${t.homeBackground}`}>
  <section className="home-hero"><div><span className="home-date">{now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</span><h1>{greeting}{profile?.displayName ? `, ${profile.displayName}` : ""}</h1></div><div className="home-hero-actions"><span className="home-week-wrap"><button className="home-chip" aria-haspopup="menu" aria-expanded={weekMenu} onClick={()=>setWeekMenu(!weekMenu)}><Icon name="calendar" size={15}/>{statsWindow==='month'?'My month':'My week'}<Icon name="chevronDown" size={13}/></button>{weekMenu&&<div className="home-week-menu" role="menu"><button data-on={statsWindow==='week'} onClick={()=>setStatsWindow('week')}>My week</button><button data-on={statsWindow==='month'} onClick={()=>setStatsWindow('month')}>My month</button></div>}</span><span className="home-chip"><Icon name="check" size={15}/>{completedInWindow} tasks completed</span><span className="home-chip"><Icon name="people" size={15}/>{people.length} collaborators</span><button className="home-chip" onClick={()=>setCustomize(true)}><Icon name="sliders" size={15}/>Customize</button></div></section>
    <OnboardingChecklist />
  <div className="home-widgets">
    {enabled('my_tasks')&&<section className="home-widget wide"><div className="widget-title-row"><div><span className="widget-icon purple"><Icon name="check" size={18}/></span><h2>My tasks</h2></div><a href="/my-tasks">Open My tasks</a></div><div className="widget-tabs">{(['upcoming','overdue','completed'] as const).map(x=><button data-active={tab===x} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="home-task-list">{visible.map(x=><button onClick={()=>setOpenId(x.id)} key={x.id}><span className={`task-check ${x.statusCategory==='done'?'done':''}`}><Icon name={x.statusCategory==='done'?'check':'circle'} size={17}/></span><span className="home-task-title">{x.title}</span><span className="home-task-project">{projects.find(p=>p.id===x.owningProjectId)?.name||x.key}</span><span className={dateKey(x.dueDate)<0?'home-due overdue':'home-due'}>{x.dueDate?new Date(x.dueDate+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):''}</span></button>)}{!visible.length&&<div className="widget-empty">No tasks in this group.</div>}</div><button className="widget-add" onClick={()=>location.assign('/quick')}><Icon name="plus" size={15}/>Add task</button></section>}
    {enabled('assigned')&&<section className="home-widget wide"><div className="widget-title-row"><div><span className="widget-icon teal"><Icon name="user" size={18}/></span><h2>Tasks I&rsquo;ve assigned</h2></div></div><p className="widget-subtitle">Track work you&rsquo;ve delegated so you can see what needs prioritizing</p><div className="home-task-list">{delegated.slice(0,6).map(x=><button onClick={()=>setOpenId(x.id)} key={x.id}><span className={`task-check ${x.statusCategory==='done'?'done':''}`}><Icon name={x.statusCategory==='done'?'check':'circle'} size={17}/></span><span className="home-task-title">{x.title}</span><span className="home-task-project">{x.ownerDisplayName||'Unassigned'}</span><span className={dateKey(x.dueDate)<0?'home-due overdue':'home-due'}>{x.dueDate?new Date(x.dueDate+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):''}</span></button>)}{!delegated.length&&<div className="widget-empty">Tasks you create and assign to teammates will appear here.</div>}</div><a className="btn btn-secondary widget-invite" href="/admin/people"><Icon name="user" size={15}/>Invite a teammate</a></section>}
    {enabled('projects')&&<section className="home-widget wide"><div className="widget-title-row"><div><span className="widget-icon coral"><Icon name="projects" size={18}/></span><h2>Projects</h2></div><div className="widget-segment"><span className="ui-segment-current">Recents</span><a href="/projects">Browse projects</a></div></div><div className="home-project-grid">{projects.slice(0,8).map(p=><a href={`/projects/${p.id}`} key={p.id}><RuntimeStyle as="span" className="home-project-icon runtime-bg" vars={{ "--runtime-bg": p.color }}>{p.name.slice(0,1)}</RuntimeStyle><strong>{p.name}</strong><small>{p.keyPrefix} · {p.health.replaceAll('_',' ')}</small></a>)}<a href="/projects" className="new-project-tile"><Icon name="plus" size={22}/><strong>New project</strong></a></div></section>}
    {enabled('people')&&<section className="home-widget"><div className="widget-title-row"><div><span className="widget-icon teal"><Icon name="people" size={18}/></span><h2>People</h2></div><a href="/admin/people">View all</a></div><p className="widget-subtitle">See who&rsquo;s on track and who needs support at a glance.</p><div className="people-stack">{people.slice(0,7).map(p=>{const s=peopleStats[p.id];return <div key={p.id}><span className="person-avatar">{p.displayName.slice(0,1)}</span><span><strong>{p.displayName}</strong><small>{p.email}</small></span>{s&&<span className="person-stats"><b className={s.overdue?'stat-overdue':''}>{s.overdue} overdue</b><b className={s.completed?'stat-completed':''}>{s.completed} completed</b><b>{s.upcoming} upcoming</b></span>}</div>})}</div></section>}
    <button className="home-add-widget" onClick={()=>setCustomize(true)}><Icon name="plus" size={20}/>Customize home</button>
  </div>
  {customize&&<><button className="drawer-overlay" onClick={()=>setCustomize(false)} aria-label="Close customize"/><aside className="home-customize"><div className="drawer-head"><h2>Customize Home</h2><button className="icon-btn" aria-label="Close customize panel" onClick={()=>setCustomize(false)}><Icon name="close"/></button></div><p>Choose the widgets that appear on your Home page.</p>{['my_tasks','assigned','projects','people'].map(k=><label className="setting-row" key={k}><span><strong>{k.replace('_',' ')}</strong></span><span className="switch"><input type="checkbox" checked={enabled(k)} onChange={()=>toggleWidget(k)}/><span/></span></label>)}<a className="btn btn-block" href="/settings/display">Background & theme</a></aside></>}
  {openId&&<TaskDrawer id={openId} onClose={()=>setOpenId(null)} onSaved={load}/>} 
</div>}
