"use client";
import { appPrompt } from "../../../../../components/ui/AppDialog";
import { useEffect,useMemo,useRef,useState } from "react";
import {useParams} from "next/navigation";
import {api,ApiError} from "../../../../../lib/api";
import {ProjectChrome} from "../../../../../components/project/ProjectChrome";
import {TaskDrawer} from "../../../../../components/work/TaskDrawer";
import {Button,Icon,Select,Switch,Textarea} from "../../../../../components/ui";
import {useToast} from "../../../../../components/ui/Toast";

type Project={id:string;name:string;keyPrefix:string;color?:string;icon?:string|null;health:string;status:string;privacy:string;version:number;description?:string|null;startDate?:string|null;dueDate?:string|null;ownerUserId?:string};
type Item={id:string;key:string;title:string;typeKey?:string;statusCategory:string;dueDate:string|null;updatedAt:string};
type Member={id:string;userId:string;displayName:string;email:string;accessLevel:string};
type Update={id:string;health:string;title?:string;headline?:string;body:string|null;createdAt:string};
type Resource={id:string;kind:string;name:string;url:string|null;body:string|null};
type Goal={id:string;name:string;progress?:number}; type Portfolio={id:string;name:string};
type PortfolioLink={portfolioId:string;portfolioName:string;projectId:string};
type Brief={id:string|null;body:string|null};
type Activity={id:string;kind:string;text:string|null;at:string;actorName:string};
type AiSettings={includeSources:boolean;includeRiskReport:boolean;regularUpdates:boolean;timeframe:string;summary:string|null;generatedAt:string|null;degraded?:boolean};

export default function Overview(){
  const id=useParams().id as string; const toast=useToast();
  const [project,setProject]=useState<Project|null>(null);const [items,setItems]=useState<Item[]>([]);const [members,setMembers]=useState<Member[]>([]);const [updates,setUpdates]=useState<Update[]>([]);const [resources,setResources]=useState<Resource[]>([]);const [openId,setOpenId]=useState<string|null>(null);
  const [goals,setGoals]=useState<Goal[]>([]);const [goalPick,setGoalPick]=useState("");const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolioPick,setPortfolioPick]=useState("");const [portfolioLinks,setPortfolioLinks]=useState<PortfolioLink[]>([]);
  const [brief,setBrief]=useState("");const [briefSaved,setBriefSaved]=useState(true);const [activity,setActivity]=useState<Activity[]>([]);const [ai,setAi]=useState<AiSettings|null>(null);const [aiBusy,setAiBusy]=useState(false);
  async function load(){
    const [p,i,m,u,r,g,ports,links,b,a,aiRow]=await Promise.all([
      api<Project>(`/projects/${id}`,{org:true}), api<Item[]>(`/projects/${id}/work-items?limit=500`,{org:true}).catch(()=>[]), api<Member[]>(`/projects/${id}/members`,{org:true}).catch(()=>[]), api<Update[]>(`/projects/${id}/status-updates`,{org:true}).catch(()=>[]), api<Resource[]>(`/projects/${id}/resources`,{org:true}).catch(()=>[]), api<Goal[]>('/goals',{org:true}).catch(()=>[]), api<Portfolio[]>('/portfolios',{org:true}).catch(()=>[]), api<PortfolioLink[]>('/portfolio-projects',{org:true}).catch(()=>[]), api<Brief>(`/projects/${id}/brief`,{org:true}).catch(()=>({id:null,body:''})), api<Activity[]>(`/projects/${id}/activity-timeline`,{org:true}).catch(()=>[]), api<AiSettings>(`/ai/projects/${id}/summary`,{org:true}).catch(()=>null),
    ]);
    setProject(p);setItems(i);setMembers(m);setUpdates(u);setResources(r);setGoals(g);setPortfolios(ports);setPortfolioLinks(links);setBrief(b.body||"");setBriefSaved(true);setActivity(a);setAi(aiRow);
  }
  useEffect(()=>{load().catch(()=>{})},[id]);
  const milestones=useMemo(()=>items.filter(x=>x.typeKey==='milestone').slice(0,8),[items]);
  async function addResource(){const name=await appPrompt('Resource name');if(!name)return;const url=await appPrompt('URL (optional)')||undefined;await api(`/projects/${id}/resources`,{method:'POST',org:true,body:JSON.stringify({name,kind:'link',url})});load()}
  async function connectGoal(){if(!goalPick)return;await api(`/goals/${goalPick}/links`,{method:'POST',org:true,body:JSON.stringify({kind:'project',refId:id})});toast({message:'Goal connected',tone:'success'});setGoalPick('')}
  async function createGoal(){const name=await appPrompt('Goal name');if(!name?.trim())return;const row=await api<Goal>('/goals',{method:'POST',org:true,body:JSON.stringify({name:name.trim(),targetType:'percent',startValue:0,targetValue:100,currentValue:0})});await api(`/goals/${row.id}/links`,{method:'POST',org:true,body:JSON.stringify({kind:'project',refId:id})});toast({message:'Goal created and connected',tone:'success'});load()}
  async function addToPortfolio(){if(!portfolioPick)return;try{await api(`/portfolios/${portfolioPick}/projects`,{method:'POST',org:true,body:JSON.stringify({projectId:id})});toast({message:'Project added to portfolio',tone:'success'});setPortfolioPick('');load()}catch(e){toast({message:e instanceof ApiError?e.message:'Could not add project',tone:'error'})}}
  async function saveBrief(){await api(`/projects/${id}/brief`,{method:'PUT',org:true,body:JSON.stringify({body:brief})});setBriefSaved(true);toast({message:'Project brief saved',tone:'success'});setActivity(await api<Activity[]>(`/projects/${id}/activity-timeline`,{org:true}).catch(()=>activity))}
  async function updateAi(patch:Partial<Pick<AiSettings,'includeSources'|'includeRiskReport'|'regularUpdates'|'timeframe'>>){if(!ai)return;setAi({...ai,...patch});try{setAi(await api<AiSettings>(`/ai/projects/${id}/summary`,{method:'PATCH',org:true,body:JSON.stringify(patch)}))}catch(e){toast({message:e instanceof ApiError?e.message:'Could not save AI settings',tone:'error'})}}
  async function generateAi(){setAiBusy(true);try{setAi(await api<AiSettings>(`/ai/projects/${id}/summary/generate`,{method:'POST',org:true}));toast({message:'Project summary updated',tone:'success'})}catch(e){toast({message:e instanceof ApiError?e.message:'AI summary unavailable',tone:'error'})}finally{setAiBusy(false)}}
  if(!project)return <div className="asana-loading-page">Loading project…</div>;
  const linkedPortfolioNames=portfolioLinks.filter(x=>x.projectId===id).map(x=>x.portfolioName);
  return <><ProjectChrome project={project} view="overview" onProjectChange={load}/><div className="overview-grid"><main className="overview-main">
    <section className="overview-ai-card"><div className="overview-section-title"><span><Icon name="sparkles" size={18}/>Project summary</span><Button size="compact" variant="secondary" onClick={generateAi} disabled={aiBusy||!ai}>{aiBusy?'Generating…':ai?.summary?'Regenerate':'Generate'}</Button></div><p>{ai?.summary||project.description||`Track ${items.length} work items, recent decisions, risks, and milestones for ${project.name}.`}</p><div className="overview-ai-stats"><span><strong>{items.filter(x=>x.statusCategory==='done').length}</strong> completed</span><span><strong>{items.filter(x=>x.statusCategory==='in_progress').length}</strong> in progress</span><span><strong>{items.filter(x=>x.dueDate&&new Date(x.dueDate)<new Date()&&x.statusCategory!=='done').length}</strong> overdue</span></div>{ai&&<div className="overview-ai-controls"><Switch label="Include sources" checked={ai.includeSources} onChange={includeSources=>updateAi({includeSources})}/><Switch label="Include risk report" checked={ai.includeRiskReport} onChange={includeRiskReport=>updateAi({includeRiskReport})}/><Switch label="Regular updates" description="Keep this project opted into scheduled summary generation when the AI automation runner is enabled." checked={ai.regularUpdates} onChange={regularUpdates=>updateAi({regularUpdates})}/><label>Summary window<Select value={ai.timeframe} onChange={e=>updateAi({timeframe:e.target.value})}><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></Select></label>{ai.generatedAt&&<small>Generated {new Date(ai.generatedAt).toLocaleString()}</small>}</div>}</section>

    <section className="overview-card project-brief-card"><div className="overview-section-title"><span>Project brief</span><span>{briefSaved?'Saved':'Unsaved changes'}</span></div><BriefEditor value={brief} onChange={(v)=>{setBrief(v);setBriefSaved(false)}}/><div className="brief-actions"><Button variant="primary" onClick={saveBrief} disabled={briefSaved}>Save brief</Button><small>Formatting is stored as portable Markdown so project content stays safe and exportable.</small></div></section>

    <section className="overview-card"><div className="overview-section-title"><span>Goals</span><a href="/goals">Open goals</a></div><div className="overview-connect-controls"><Select value={goalPick} onChange={e=>setGoalPick(e.target.value)}><option value="">Connect existing goal…</option>{goals.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</Select><Button variant="secondary" disabled={!goalPick} onClick={connectGoal}>Connect</Button><Button variant="tertiary" onClick={createGoal}><Icon name="plus" size={14}/>Create goal</Button></div></section>

    <section className="overview-card"><div className="overview-section-title"><span>Portfolios</span><a href="/portfolios">Open portfolios</a></div>{linkedPortfolioNames.length>0&&<div className="connected-chip-list">{linkedPortfolioNames.map(x=><span key={x}>{x}</span>)}</div>}<div className="overview-connect-controls"><Select value={portfolioPick} onChange={e=>setPortfolioPick(e.target.value)}><option value="">Add to portfolio…</option>{portfolios.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</Select><Button variant="secondary" disabled={!portfolioPick} onClick={addToPortfolio}>Add</Button></div></section>

    <section className="overview-card"><div className="overview-section-title"><span>Project roles</span><button className="text-button" onClick={()=>document.querySelector<HTMLButtonElement>('.project-head-actions .btn')?.click()}>Manage members</button></div><div className="role-grid">{members.slice(0,8).map(m=><div key={m.id}><span className="mini-avatar">{m.displayName.slice(0,1)}</span><span><strong>{m.displayName}</strong><small>{m.accessLevel.replace('_',' ')}</small></span></div>)}</div></section>
    <section className="overview-card"><div className="overview-section-title"><span>Key resources</span><button className="text-button" onClick={addResource}><Icon name="plus" size={14}/>Add resource</button></div>{resources.filter(r=>r.kind!=='brief').length===0?<div className="overview-empty">Pin docs, dashboards, and important links here.</div>:<div className="resource-list">{resources.filter(r=>r.kind!=='brief').map(r=><a key={r.id} href={r.url||'#'} target={r.url?'_blank':undefined}><Icon name={r.kind==='file'?'paperclip':'link'} size={16}/><span><strong>{r.name}</strong><small>{r.body||r.url||r.kind}</small></span></a>)}</div>}</section>
    <section className="overview-card"><div className="overview-section-title"><span>Milestones</span><a href={`/projects/${id}/timeline`}>View timeline</a></div>{milestones.length===0?<div className="overview-empty">Add a milestone from the Add task menu.</div>:milestones.map(x=><button className="milestone-row" key={x.id} onClick={()=>setOpenId(x.id)}><span className="milestone-diamond">◆</span><span>{x.title}</span><time>{x.dueDate||'No due date'}</time></button>)}</section>
    <section className="overview-card"><div className="overview-section-title"><span>Project activity & status timeline</span><span>{activity.length} events</span></div>{activity.length===0?<div className="overview-empty">Project changes and status updates will appear here.</div>:<div className="project-activity-list">{activity.slice(0,30).map(row=><article key={`${row.kind}-${row.id}`}><span className="activity-marker"/><div><strong>{row.text||row.kind.replaceAll('_',' ')}</strong><small>{row.actorName} · {new Date(row.at).toLocaleString()}</small></div></article>)}</div>}</section>
  </main><aside className="overview-side"><section className="overview-side-card"><h3>Project details</h3><dl><div><dt>Status</dt><dd>{project.status.replace('_',' ')}</dd></div><div><dt>Health</dt><dd>{project.health.replace('_',' ')}</dd></div><div><dt>Dates</dt><dd>{project.startDate||'—'} → {project.dueDate||'—'}</dd></div><div><dt>Members</dt><dd>{members.length}</dd></div><div><dt>Privacy</dt><dd>{project.privacy}</dd></div></dl></section><section className="overview-side-card"><h3>Recent status</h3>{updates.slice(0,4).map(u=><article className="status-update-mini" key={u.id}><span data-health={u.health}/><div><strong>{u.headline||u.title}</strong><small>{new Date(u.createdAt).toLocaleDateString()}</small></div></article>)}{!updates.length&&<p className="muted">No status updates yet.</p>}</section><section className="overview-side-card"><h3>Connected work</h3><a className="overview-connect" href="/goals"><Icon name="goal" size={16}/>Goals</a><a className="overview-connect" href="/portfolios"><Icon name="portfolio" size={16}/>Portfolios</a><a className="overview-connect" href="/devops"><Icon name="release" size={16}/>Development links</a></section></aside></div>{openId&&<TaskDrawer id={openId} onClose={()=>setOpenId(null)} onSaved={load}/>}</>;
}

function BriefEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
  const history=useRef<string[]>([]); const future=useRef<string[]>([]);
  const getEl=()=>document.getElementById("project-brief-editor") as HTMLTextAreaElement|null;
  function commit(next:string,selection?:[number,number]){if(next===value)return;history.current=[...history.current.slice(-49),value];future.current=[];onChange(next);if(selection)requestAnimationFrame(()=>{const el=getEl();if(!el)return;el.focus();el.setSelectionRange(selection[0],selection[1])})}
  function wrap(before:string,after=before,placeholder='text'){const el=getEl();if(!el)return;const start=el.selectionStart,end=el.selectionEnd,selected=value.slice(start,end)||placeholder;const next=value.slice(0,start)+before+selected+after+value.slice(end);commit(next,[start+before.length,start+before.length+selected.length])}
  function line(prefix:string){const el=getEl();if(!el)return;const start=el.selectionStart,end=el.selectionEnd;const selected=value.slice(start,end)||'item';const inserted=selected.split('\n').map(x=>prefix+x).join('\n');commit(value.slice(0,start)+inserted+value.slice(end),[start,start+inserted.length])}
  function undo(){const previous=history.current.pop();if(previous===undefined)return;future.current=[value,...future.current.slice(0,49)];onChange(previous)}
  function redo(){const next=future.current.shift();if(next===undefined)return;history.current=[...history.current.slice(-49),value];onChange(next)}
  async function insertLink(){const label=await appPrompt('Link text','link text');if(label===null)return;const url=await appPrompt('Link URL','https://');if(!url?.trim())return;wrap('[',`](${url.trim()})`,label.trim()||url.trim())}
  async function insertObject(){const title=await appPrompt('Object title','Project resource');if(!title?.trim())return;const url=await appPrompt('Object URL','https://');if(!url?.trim())return;const el=getEl();const start=el?.selectionStart??value.length;const block=`\n[${title.trim()}](${url.trim()})\n`;commit(value.slice(0,start)+block+value.slice(start),[start+1,start+block.length-1])}
  return <div className="brief-editor"><div className="brief-toolbar" role="toolbar" aria-label="Project brief formatting">
    <button type="button" onClick={undo} aria-label="Undo">Undo</button><button type="button" onClick={redo} aria-label="Redo">Redo</button><button type="button" onClick={insertObject} aria-label="Insert object">Insert object</button>
    <button type="button" onClick={()=>wrap('**')} aria-label="Bold"><b>B</b></button><button type="button" onClick={()=>wrap('_')} aria-label="Italic"><i>I</i></button><button type="button" onClick={()=>wrap('<u>','</u>')} aria-label="Underline"><u>U</u></button><button type="button" onClick={()=>wrap('<mark>','</mark>')} aria-label="Highlight">Highlight</button><button type="button" onClick={()=>wrap('~~')} aria-label="Strikethrough"><s>S</s></button>
    <button type="button" onClick={()=>line('- ')} aria-label="Bulleted list">• List</button><button type="button" onClick={()=>line('1. ')} aria-label="Numbered list">1. List</button><button type="button" onClick={()=>line('> ')} aria-label="Quote">Quote</button><button type="button" onClick={()=>wrap('`')} aria-label="Inline code">Code</button><button type="button" onClick={insertLink} aria-label="Link">Link</button><button type="button" onClick={()=>line('## ')} aria-label="Heading">Heading</button>
  </div><Textarea id="project-brief-editor" value={value} onChange={e=>commit(e.target.value)} rows={12} placeholder="Write the project brief: purpose, scope, goals, requirements, decisions, and links…"/></div>
}
