"use client";

import { Button, Select as UiSelect, Switch } from "../../../components/ui";
import { appPrompt } from "../../../components/ui/AppDialog";
import { useEffect, useMemo, useState } from "react";
import { api } from "../../../lib/api";
import { Icon } from "../../../components/ui/Icon";
import { TaskDrawer } from "../../../components/work/TaskDrawer";
import { useTheme } from "../../../components/theme/ThemeProvider";
import { useToast } from "../../../components/ui/Toast";

type Notif={id:string;type:string;data:string|null;workItemId:string|null;readAt:string|null;bookmarkedAt:string|null;archivedAt:string|null;createdAt:string};
type Tab='activity'|'bookmarks'|'archive'|'mentioned';
type InboxFilter='all'|'unread'|'assigned'|'mentions';
type Sort='newest'|'relevance';
type SavedView={id:string;name:string;filters?:{filter?:InboxFilter;tab?:Tab;sort?:Sort}};
type Summary={enabled:boolean;timeframe:string;summary:string|null;counts?:Record<string,number>;unread?:number;degraded?:boolean};
const labels:{id:Tab;label:string}[]=[{id:'activity',label:'Activity'},{id:'bookmarks',label:'Bookmarks'},{id:'archive',label:'Archive'},{id:'mentioned',label:'@Mentioned'}];

export default function Inbox(){
  const theme=useTheme(); const toast=useToast();
  const [tab,setTab]=useState<Tab>('activity'); const [rows,setRows]=useState<Notif[]>([]); const [loading,setLoading]=useState(true);
  const [filter,setFilter]=useState<InboxFilter>('all'); const [sort,setSort]=useState<Sort>('newest'); const [density,setDensity]=useState<'detailed'|'compact'>('detailed');
  const [openId,setOpenId]=useState<string|null>(null); const [saved,setSaved]=useState<SavedView[]>([]); const [summary,setSummary]=useState<Summary|null>(null); const [summaryBusy,setSummaryBusy]=useState(false);
  const summaryEnabled=theme.preferences.inboxSummaryEnabled; const timeframe=theme.preferences.inboxSummaryTimeframe||'week';

  const [loadError,setLoadError]=useState('');
  async function load(){setLoading(true);try{setRows(await api<Notif[]>(`/notifications?tab=${tab}&sort=${sort}`,{org:true}));setLoadError('')}catch(e){setLoadError(e instanceof Error?e.message:'Could not load your inbox.')}finally{setLoading(false)}}
  async function loadSummary(){if(!summaryEnabled){setSummary(null);return;}setSummaryBusy(true);try{setSummary(await api<Summary>(`/ai/inbox-summary?timeframe=${timeframe}`,{org:true}))}catch{setSummary({enabled:true,timeframe,summary:'Inbox summary is unavailable until the AI module/provider is enabled.'})}finally{setSummaryBusy(false)}}
  useEffect(()=>{load()},[tab,sort]);
  useEffect(()=>{api<SavedView[]>('/ui/saved-views?scopeType=inbox',{org:true}).then(setSaved).catch(()=>{})},[]);
  useEffect(()=>{loadSummary().catch(()=>{})},[summaryEnabled,timeframe]);
  const visible=useMemo(()=>rows.filter(n=>filter==='all'||filter==='unread'&&!n.readAt||filter==='assigned'&&n.type==='assigned'||filter==='mentions'&&n.type==='mention'),[rows,filter]);
  async function mark(n:Notif){if(n.workItemId)setOpenId(n.workItemId);if(!n.readAt){try{await api(`/notifications/${n.id}/read`,{method:'POST',org:true});load()}catch(err){toast({message:err instanceof Error?err.message:'Could not mark as read',tone:'error'})}}}
  async function bookmark(n:Notif){try{await api(`/notifications/${n.id}/bookmark`,{method:n.bookmarkedAt?'DELETE':'POST',org:true});load()}catch(err){toast({message:err instanceof Error?err.message:'Could not update the bookmark',tone:'error'})}}
  async function archive(n:Notif){try{await api(`/notifications/${n.id}/archive`,{method:n.archivedAt?'DELETE':'POST',org:true});load()}catch(err){toast({message:err instanceof Error?err.message:'Could not archive the notification',tone:'error'})}}
  async function saveTab(){const name=await appPrompt('Saved tab name','My inbox view');if(!name)return;const share=await appPrompt('Share with the whole organization? Type "org" to share, or leave blank to keep it just for you.','');const ownershipTier=(share||'').trim().toLowerCase()==='org'?'org':'personal';const created=await api<SavedView>('/ui/saved-views',{method:'POST',org:true,body:JSON.stringify({scopeType:'inbox',name,viewType:'inbox',filters:{filter,tab,sort},ownershipTier})});setSaved(v=>[...v,created])}
  function applySaved(v:SavedView){if(v.filters?.tab&&labels.some(x=>x.id===v.filters?.tab))setTab(v.filters.tab);if(v.filters?.filter&&['all','unread','assigned','mentions'].includes(v.filters.filter))setFilter(v.filters.filter);if(v.filters?.sort)setSort(v.filters.sort)}
  async function archiveAll(){try{const result=await api<{archived:number}>('/notifications/archive-all',{method:'POST',org:true});toast({message:`${result.archived} notifications archived`,tone:'success'});await load();await loadSummary()}catch(err){toast({message:err instanceof Error?err.message:'Could not archive notifications',tone:'error'})}}
  function clearFilters(){setFilter('all');setSort('newest')}

  return <div className="inbox-page"><header className="asana-page-title"><h1>Inbox</h1><a href="/settings/notifications">Manage notifications</a></header>
    <div className="inbox-tabs">{labels.map(x=><button data-active={tab===x.id} onClick={()=>setTab(x.id)} key={x.id}>{x.label}</button>)}{saved.map(v=><button key={v.id} onClick={()=>applySaved(v)}>{v.name}</button>)}<button className="tab-plus" aria-label="Save current inbox view" onClick={saveTab}><Icon name="plus" size={15}/></button></div>
    {summaryEnabled&&tab==='activity'&&<section className="inbox-summary-card" aria-live="polite"><div className="inbox-summary-head"><span><Icon name="sparkles" size={17}/><strong>Inbox Summary</strong></span><div><UiSelect aria-label="Summary timeframe" value={timeframe} onChange={e=>theme.setPreferences({inboxSummaryTimeframe:e.target.value})}><option value="day">Today</option><option value="week">Last 7 days</option><option value="month">Last 30 days</option></UiSelect><Button variant="tertiary" size="compact" onClick={loadSummary} disabled={summaryBusy}>{summaryBusy?'Refreshing…':'Refresh'}</Button></div></div><p>{summaryBusy?'Generating summary…':summary?.summary||'No summary is available yet.'}</p><button className="text-button" onClick={()=>theme.setPreferences({inboxSummaryEnabled:false})}>Turn off Inbox Summary</button></section>}
    {!summaryEnabled&&<div className="inbox-summary-off"><span>Inbox Summary is off.</span><button className="text-button" onClick={()=>theme.setPreferences({inboxSummaryEnabled:true})}>Turn on</button></div>}
    <div className="inbox-toolbar"><label className="toolbar-button"><Icon name="filter" size={15}/>Filter<UiSelect value={filter} onChange={e=>setFilter(e.target.value as InboxFilter)}><option value="all">All activity</option><option value="unread">Unread</option><option value="assigned">Assigned to me</option><option value="mentions">Mentioned</option></UiSelect></label><label className="toolbar-button"><Icon name="sort" size={15}/>Sort<UiSelect value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="newest">Newest</option><option value="relevance">Relevance</option></UiSelect></label><label className="toolbar-button"><Icon name="list" size={15}/>Density<UiSelect value={density} onChange={e=>setDensity(e.target.value as 'detailed'|'compact')}><option value="detailed">Detailed</option><option value="compact">Compact</option></UiSelect></label><span className="spacer"/><button className="toolbar-button" onClick={async()=>{await api('/notifications/read-all',{method:'POST',org:true});load()}}>Mark all read</button>{tab==='activity'&&<button className="toolbar-button" onClick={archiveAll}>Archive all</button>}</div>
    <section className="inbox-list" data-density={density}>{loading&&<div className="inbox-zero">Loading…</div>}{!loading&&loadError&&<div className="inbox-zero"><span className="zero-illustration"><Icon name="bell" size={40}/></span><h2>Could not load your inbox</h2><p>{loadError}</p><Button variant="secondary" size="compact" onClick={load}>Retry</Button></div>}{!loading&&!loadError&&!visible.length&&<div className="inbox-zero"><span className="zero-illustration"><Icon name="inbox" size={40}/></span><h2>You’re all caught up</h2><p>{filter==='all'?'New assignments, mentions and project updates will appear here.':'No notifications match the active filters.'}</p>{filter!=='all'&&<Button variant="secondary" size="compact" onClick={clearFilters}>Clear filters</Button>}</div>}{!loadError&&visible.map(n=><article className="inbox-item" data-unread={!n.readAt} key={n.id}><button className="inbox-open" onClick={()=>mark(n)}><span className={`inbox-type ${n.type}`}><Icon name={n.type==='mention'?'comment':n.type==='assigned'?'check':'bell'} size={17}/></span><span className="inbox-copy"><strong>{title(n)}</strong>{density==='detailed'&&<small>{n.data||'Open the related work item to see the full update.'}</small>}</span><time>{new Date(n.createdAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></button><div className="inbox-item-actions"><button data-on={!!n.bookmarkedAt} onClick={()=>bookmark(n)} title="Bookmark" aria-label="Bookmark notification"><Icon name="star" size={16}/></button><button onClick={()=>archive(n)} title={n.archivedAt?'Restore':'Archive'} aria-label={n.archivedAt?'Restore notification':'Archive notification'}><Icon name={n.archivedAt?'arrowLeft':'inbox'} size={16}/></button></div></article>)}</section>{openId&&<TaskDrawer id={openId} onClose={()=>setOpenId(null)} onSaved={load}/>}</div>;
}
function title(n:Notif){switch(n.type){case'mention':return'You were mentioned';case'assigned':return'A task was assigned to you';case'comment':return'New comment on work you follow';case'watch':return'An item you follow was updated';default:return'Workspace update'}}
